# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven


    # - name: Install VPN
    #   run: | 
    #         sudo apt update
    #         sudo apt install openvpn
    #         cd src
    #         cd data
    #         ls

    #         sudo chmod -R 777 /etc/openvpn
    #         #sudo touch /etc/openvpn/credentials
    #         #sudo printf '%s\n' 'vpnbook' 'mbr7ahx' > /etc/openvpn/credentials
    #         sudo sed -i 's/auth-user-pass/auth-user-pass credentials/g' data.ovpn

    #         sudo nohup openvpn data.ovpn &
    #         curl ifconfig.me
            

      # Start Xvfb
    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      
        
    - name: Download ChromeDriver
      run: | 
          
          # Download Chrome version 114.0.5735.90
          wget -q "https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_114.0.5735.90-1_amd64.deb" -O chrome.deb
          # Install Chrome
          sudo dpkg -i chrome.deb
          # Install dependencies
          sudo apt-get install -f
          # Clean up
          rm chrome.deb
          LATEST_CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          wget "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -P ~/
          unzip ~/chromedriver_linux64.zip -d ~/ && rm ~/chromedriver_linux64.zip
          sudo mv -f ~/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          # CHROMEDRIVER_VERSION=$(curl -s https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          # wget -q -O /tmp/chromedriver.zip "https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip"
          # sudo unzip -o /tmp/chromedriver.zip -d /usr/local/bin/
          # sudo chmod +x /usr/local/bin/chromedriver


    - name: Check Chrome Version
      run: google-chrome --version


    - name: Verify installation
      run: chromedriver --version
    
    - name: Build with Maven
      run: mvn clean install -B

    - name: test with Maven
      run: sudo xvfb-run -a mvn -B clean test

    - name: Commit and Push Changes
      run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add /home/runner/work/gitActionWindows/gitActionWindows/screenshots/
          git commit -m "Automatically updated GitHub Actions workflow"
          git push
        # Display output
    - run: echo "Changes committed and pushed successfully"
        
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

      
